spring.application.name=MMT
server.port=8080
spring.security.user.name=admin
spring.security.user.password=secure123
spring.mongodb.uri=mongodb+srv://Prit:pritprit@main.9axdfel.mongodb.net/MMTClone?retryWrites=true&w=majority&appName=Main